#!/bin/sh

set -e

MIN_MEMORY=${MIN_MEMORY:=512M}
MAX_MEMORY=${MAX_MEMORY:=1G}
SERVER_ARGUMENTS=${SERVER_ARGUMENTS:=$@}
$JAVA_FLAGS=${$JAVA_FLAGS:=$@}

java -Xms$MIN_MEMORY -Xmx$MAX_MEMORY $JAVA_FLAGS -jar /opt/shiruka/Shiruka.jar $SERVER_ARGUMENTS