files:
  - source: shiruka/texts/en_US.lang
    translation: /shiruka/texts/%locale_with_underscore%.%file_extension%
  - source: shiruka/configs/en_US.lang
    translation: /shiruka/configs/%locale_with_underscore%.%file_extension%
